#include "main.h"

#ifdef __WIN32__
#define UTOX_RGB(r, g, b) ( ((b)<<16) | ((g)<<8) | (r) )
#else
#define UTOX_RGB(r, g, b) ( ((r)<<16) | ((g)<<8) | (b) )
#endif

void theme_load(char loadtheme)
{
    // Update the settings dropdown UI
    dropdown_theme.selected = loadtheme;

    // ==== Default theme ====
    //---- Main chat area ----
    COLOR_MAIN_BACKGROUND = UTOX_RGB(FF, FF, FF);
    COLOR_MAIN_TEXT       = UTOX_RGB(33, 33, 33);
    COLOR_MAIN_SUBTEXT    = UTOX_RGB(59, 59, 59);
    COLOR_MAIN_ACTIONTEXT = UTOX_RGB(44, 44, ff);
    COLOR_MAIN_QUOTETEXT  = UTOX_RGB(00, 88, 00);
    COLOR_MAIN_URLTEXT    = UTOX_RGB(4E, A6, EA);

    //---- Top & bottom menu colours ----
    COLOR_MENU_BACKGROUND        = UTOX_RGB(1c, 1c, 1c);
    COLOR_MENU_TEXT              = UTOX_RGB(C0, C0, C0);
    COLOR_MENU_HOVER_BACKGROUND  = UTOX_RGB(20, 20, 20);
    COLOR_MENU_ACTIVE_BACKGROUND = UTOX_RGB(40, 40, 40);
    COLOR_MENU_ACTIVE_TEXT       = UTOX_RGB(E5, E5, E5);

    //---- Friend list  ----
    COLOR_LIST_BACKGROUND       = UTOX_RGB(28, 28, 28);
    COLOR_LIST_HOVER_BACKGROUND = UTOX_RGB(55, 55, 55);
    COLOR_LIST_TEXT             = COLOR_MAIN_BACKGROUND;
    COLOR_LIST_SUBTEXT          = UTOX_RGB(Ba, Ba, Ba);

    //---- Text selection ----
    COLOR_SELECTION_BACKGROUND = COLOR_MAIN_TEXT;
    COLOR_SELECTION_TEXT       = COLOR_MAIN_BACKGROUND;
    COLOR_GROUP_UNUSUAL        = COLOR_MAIN_URLTEXT;

    //---- Inputs, dropdowns & tooltips ----
    COLOR_EDGE_NORMAL             = UTOX_RGB(C0, C0, C0);
    COLOR_EDGE_ACTIVE             = COLOR_MAIN_URLTEXT;
    COLOR_EDGE_HOVER              = UTOX_RGB(70, 70, 70);
    COLOR_ACTIVEOPTION_BACKGROUND = UTOX_RGB(CC, CC, FF);
    COLOR_ACTIVEOPTION_TEXT       = COLOR_MAIN_TEXT;

    //---- Status circles ----
    COLOR_STATUS_ONLINE = UTOX_RGB(6b, c2, 60);
    COLOR_STATUS_AWAY   = UTOX_RGB(ce, bf, 45);
    COLOR_STATUS_BUSY   = UTOX_RGB(c8, 4e, 4e);

    //---- Buttons ---
    COLOR_BUTTON_SUCCESS_BACKGROUND       = COLOR_STATUS_ONLINE;
    COLOR_BUTTON_SUCCESS_TEXT             = COLOR_MAIN_BACKGROUND;
    COLOR_BUTTON_SUCCESS_HOVER_BACKGROUND = UTOX_RGB(76, d5, 6a);
    COLOR_BUTTON_SUCCESS_HOVER_TEXT       = COLOR_MAIN_BACKGROUND;
    COLOR_BUTTON_WARNING_BACKGROUND       = COLOR_STATUS_AWAY;
    COLOR_BUTTON_WARNING_TEXT             = COLOR_MAIN_BACKGROUND;
    COLOR_BUTTON_WARNING_HOVER_BACKGROUND = UTOX_RGB(e3, d2, 4c);
    COLOR_BUTTON_WARNING_HOVER_TEXT       = COLOR_MAIN_BACKGROUND;
    COLOR_BUTTON_DANGER_BACKGROUND        = COLOR_STATUS_BUSY;
    COLOR_BUTTON_DANGER_TEXT              = COLOR_MAIN_BACKGROUND;
    COLOR_BUTTON_DANGER_HOVER_BACKGROUND  = UTOX_RGB(dc, 56, 56);
    COLOR_BUTTON_DANGER_HOVER_TEXT        = COLOR_MAIN_BACKGROUND;
    COLOR_BUTTON_DISABLED_BACKGROUND      = UTOX_RGB(d1, d1, d1);
    COLOR_BUTTON_DISABLED_TEXT            = COLOR_MAIN_BACKGROUND;

    switch (loadtheme) {
    case THEME_DARK:
        COLOR_MAIN_BACKGROUND = UTOX_RGB(33, 33, 33);
        COLOR_MAIN_TEXT = UTOX_RGB(df, df, df);
        COLOR_MAIN_SUBTEXT = UTOX_RGB(bb, bb, bb);
        COLOR_MAIN_ACTIONTEXT = UTOX_RGB(27, a9, bc);
        COLOR_MAIN_URLTEXT = COLOR_MAIN_ACTIONTEXT;
        COLOR_MAIN_QUOTETEXT = UTOX_RGB(55, b3, 17);
        COLOR_LIST_BACKGROUND = UTOX_RGB(22, 22, 22);
        COLOR_LIST_HOVER_BACKGROUND = UTOX_RGB(15, 15, 15);
        COLOR_MENU_BACKGROUND = COLOR_LIST_BACKGROUND;
        COLOR_MENU_HOVER_BACKGROUND = COLOR_LIST_HOVER_BACKGROUND;
        COLOR_MENU_ACTIVE_BACKGROUND = COLOR_MAIN_TEXT;
        COLOR_SELECTION_BACKGROUND = COLOR_MAIN_TEXT;
        COLOR_SELECTION_TEXT = COLOR_MAIN_BACKGROUND;
        COLOR_GROUP_UNUSUAL = COLOR_MAIN_URLTEXT;
        COLOR_EDGE_NORMAL = UTOX_RGB(55, 55, 55);
        COLOR_EDGE_ACTIVE = UTOX_RGB(22, 88, 88);
        COLOR_EDGE_HOVER = UTOX_RGB(99, 99, 99);
        COLOR_ACTIVEOPTION_BACKGROUND = UTOX_RGB(22, 88, 88);
        COLOR_ACTIVEOPTION_TEXT = COLOR_MAIN_TEXT;
        COLOR_MENU_ACTIVE_TEXT = UTOX_RGB(15, 15, 15);
        COLOR_BUTTON_SUCCESS_BACKGROUND       = UTOX_RGB(41, 41, 41);
        COLOR_BUTTON_SUCCESS_TEXT             = UTOX_RGB(33, a6, 3d);
        COLOR_BUTTON_SUCCESS_HOVER_BACKGROUND = UTOX_RGB(45, 51, 47);
        COLOR_BUTTON_SUCCESS_HOVER_TEXT       = UTOX_RGB(6e, ff, 3a);
        COLOR_BUTTON_WARNING_BACKGROUND       = UTOX_RGB(41, 41, 41);
        COLOR_BUTTON_WARNING_TEXT             = UTOX_RGB(bd, 9e, 22);
        COLOR_BUTTON_WARNING_HOVER_BACKGROUND = UTOX_RGB(4c, 49, 3c);
        COLOR_BUTTON_WARNING_HOVER_TEXT       = UTOX_RGB(ff, 8d, 2a);
        COLOR_BUTTON_DANGER_BACKGROUND        = UTOX_RGB(41, 41, 41);
        COLOR_BUTTON_DANGER_TEXT              = UTOX_RGB(bd, 25, 25);
        COLOR_BUTTON_DANGER_HOVER_BACKGROUND  = UTOX_RGB(51, 39, 39);
        COLOR_BUTTON_DANGER_HOVER_TEXT        = UTOX_RGB(fa, 26, 26);
        COLOR_BUTTON_DISABLED_BACKGROUND      = UTOX_RGB(41, 41, 41);
        COLOR_BUTTON_DISABLED_TEXT            = COLOR_MAIN_BACKGROUND;
        break;

    case THEME_LIGHT:
        COLOR_LIST_BACKGROUND = UTOX_RGB(F0, F0, F0);
        COLOR_LIST_HOVER_BACKGROUND = UTOX_RGB(E0, E0, E0);
        COLOR_LIST_TEXT = COLOR_MAIN_TEXT;
        COLOR_LIST_SUBTEXT = COLOR_MAIN_SUBTEXT;
        COLOR_MENU_BACKGROUND = UTOX_RGB(F0, F0, F0);
        COLOR_MENU_HOVER_BACKGROUND = UTOX_RGB(E0, E0, E0);
        COLOR_MENU_ACTIVE_BACKGROUND = UTOX_RGB(55, 55, 55);
        COLOR_MENU_TEXT = UTOX_RGB(55, 55, 55);
        COLOR_MENU_ACTIVE_TEXT = UTOX_RGB(ff, ff, ff);
        COLOR_EDGE_NORMAL = UTOX_RGB(C0, C0, C0);
        COLOR_EDGE_ACTIVE = COLOR_MAIN_URLTEXT;
        COLOR_EDGE_HOVER = UTOX_RGB(70, 70, 70);
        COLOR_ACTIVEOPTION_BACKGROUND = UTOX_RGB(DD, EE, FF);
        COLOR_ACTIVEOPTION_TEXT = COLOR_MAIN_TEXT;
        break;

    case THEME_HIGHCONTRAST:

        COLOR_MAIN_BACKGROUND = UTOX_RGB(FF, FF, FF);
        COLOR_MAIN_TEXT = UTOX_RGB(00, 00, 01);
        COLOR_MAIN_SUBTEXT = COLOR_MAIN_TEXT;
        COLOR_MAIN_ACTIONTEXT = UTOX_RGB(00, 00, 33);
        COLOR_MAIN_QUOTETEXT = UTOX_RGB(00, 33, 00);
        COLOR_MAIN_URLTEXT = COLOR_MAIN_ACTIONTEXT;
        COLOR_MENU_BACKGROUND = COLOR_MAIN_BACKGROUND;
        COLOR_MENU_TEXT = COLOR_MAIN_TEXT;
        COLOR_MENU_HOVER_BACKGROUND = COLOR_MAIN_BACKGROUND;
        COLOR_MENU_ACTIVE_BACKGROUND = COLOR_MAIN_TEXT;
        COLOR_MENU_ACTIVE_TEXT = COLOR_MAIN_BACKGROUND;
        COLOR_LIST_BACKGROUND = UTOX_RGB(44, 44, 44);
        COLOR_LIST_HOVER_BACKGROUND = COLOR_MAIN_TEXT;
        COLOR_LIST_TEXT = COLOR_MAIN_BACKGROUND;
        COLOR_LIST_SUBTEXT = COLOR_MAIN_BACKGROUND;
        COLOR_SELECTION_BACKGROUND = COLOR_MAIN_TEXT;
        COLOR_SELECTION_TEXT = COLOR_MAIN_BACKGROUND;
        COLOR_GROUP_UNUSUAL = COLOR_MAIN_URLTEXT;
        COLOR_EDGE_NORMAL = COLOR_MAIN_TEXT;
        COLOR_EDGE_ACTIVE = COLOR_MAIN_TEXT;
        COLOR_EDGE_HOVER = COLOR_MAIN_TEXT;
        COLOR_ACTIVEOPTION_BACKGROUND = COLOR_MAIN_TEXT;
        COLOR_ACTIVEOPTION_TEXT = COLOR_MAIN_BACKGROUND;
        COLOR_STATUS_ONLINE = UTOX_RGB(00, ff, 00);
        COLOR_STATUS_AWAY   = UTOX_RGB(ff, ff, 00);
        COLOR_STATUS_BUSY   = UTOX_RGB(ff, 00, 00);
        COLOR_BUTTON_SUCCESS_BACKGROUND       = UTOX_RGB(00, ff, 00);
        COLOR_BUTTON_SUCCESS_TEXT             = COLOR_MAIN_BACKGROUND;
        COLOR_BUTTON_SUCCESS_HOVER_BACKGROUND = UTOX_RGB(00, ff, 00);
        COLOR_BUTTON_SUCCESS_HOVER_TEXT       = COLOR_MAIN_BACKGROUND;
        COLOR_BUTTON_WARNING_BACKGROUND       = UTOX_RGB(ff, ff, 00);
        COLOR_BUTTON_WARNING_TEXT             = COLOR_MAIN_BACKGROUND;
        COLOR_BUTTON_WARNING_HOVER_BACKGROUND = UTOX_RGB(ff, ff, 00);
        COLOR_BUTTON_WARNING_HOVER_TEXT       = COLOR_MAIN_BACKGROUND;
        COLOR_BUTTON_DANGER_BACKGROUND        = UTOX_RGB(ff, 00, 00);
        COLOR_BUTTON_DANGER_TEXT              = COLOR_MAIN_BACKGROUND;
        COLOR_BUTTON_DANGER_HOVER_BACKGROUND  = UTOX_RGB(ff, 00, 00);
        COLOR_BUTTON_DANGER_HOVER_TEXT        = COLOR_MAIN_BACKGROUND;
        COLOR_BUTTON_DISABLED_BACKGROUND      = UTOX_RGB(44, 44, 44);
        COLOR_BUTTON_DISABLED_TEXT            = COLOR_MAIN_TEXT;
        break;
    }
    status_color[0] = COLOR_STATUS_ONLINE;
    status_color[1] = COLOR_STATUS_AWAY;
    status_color[2] = COLOR_STATUS_BUSY;
    status_color[3] = COLOR_STATUS_BUSY;
}
